### ISSUE TITLE
Proposal async validation

### ISSUE THREAD

**Issue by kronic** [Karnah/ReactiveValidation#19]
Add support async validation.

**Comment by Karnah** [comment]
Hello, @kronic! This is in plans of release 2.0 #18 
Unfortunately, I cannot say anything about when I can do this.

**Comment by MarkusKgit** [comment]
I'm just curious - what is the use case here? Validation that has to query I/O or web?

**Comment by Karnah** [comment]
Hi, @kronic. There are a lot time passed, but I've completed this feature :)
You can test it on [2.0.0-pre](https://www.nuget.org/packages/ReactiveValidation.Wpf/2.0.0-pre) version.
How use it describted [here](https://github.com/Karnah/ReactiveValidation/wiki/Async-validation)

``` c#
builder.RuleFor(vm => vm.Email)
    .NotEmpty().When(vm => vm.PhoneNumber, phoneNumber => string.IsNullOrEmpty(phoneNumber))
    .Must(IsValidEmail)
    .Must(CheckEmailIsInUseAsync).WithMessage("Email is already using");

...

/// <summary>
/// Check of email is valid.
/// </summary>
private static bool IsValidEmail(string? email)
{
    // Some sync logic.
}

/// <summary>
/// Async check that email is already using.
/// </summary>
private static async Task<bool> CheckEmailIsInUseAsync(string? email, CancellationToken cancellationToken)
{
    // Some async logic.
}
```
