### ISSUE TITLE
Проблема при использовании не базовых классов как свойств

### ISSUE THREAD

**Issue by PeskovV** [Karnah/ReactiveValidation#20]
Я создал класс

```c#
public class SectionViewModel : BaseViewModel
    {
        private string _nameSection;
        public string NameSection
        {
            get { return _nameSection; }
            set
            {
                _nameSection = value;
                OnPropertyChanged(nameof(NameSection));
            }
        }

        private int _risk;
        public int Risk
        {
            get { return _risk; }
            set
            {
                _risk = value;
                OnPropertyChanged(nameof(Risk));
            }
        }
    }
```

```c#
private SectionViewModel _selectedSection;
        public SectionViewModel SelectedSection
        {
            get => _selectedSection;
            set
            {
                _selectedSection = value;
                OnPropertyChanged(nameof(SelectedSection));
            }
        }
```

Так устанавливаю правила во ViewModel, где находится свойство SelectedSection
```c#
var organizationBuilder = new ValidationBuilder<OrganizationViewModel>();
organizationBuilder.RuleFor(x => x.SelectedSection).NotNull().WithMessage("текст");
```

SelectedSection используется для биндинга в SelectedItem в ComboBox. Если стереть выбранное значение в ComboBox, то в SelectedSection придёт null и произойдёт ошибка.

Причём при старте приложения SelectedSection = null, но приложение не падает

> System.NullReferenceException
>   HResult=0x80004003
>   Message=Ссылка на объект не указывает на экземпляр объекта.
>   Source=ReactiveValidation
>   StackTrace:
>    at ReactiveValidation.Adapters.SinglePropertyAdapter`2.NotifyPropertyChangedSubsriber..ctor(INotifyPropertyChanged property, Action action)
>    at ReactiveValidation.Adapters.SinglePropertyAdapter`2.<>c.<GetObserverBuilders>b__1_0(TObject o, TProp prop, Action action)
>    at ReactiveValidation.Adapters.BaseSinglePropertyAdapter`2.<>c__DisplayClass6_0.<ResubscribeProperty>b__0(Func`4 ob)
>    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at ReactiveValidation.Adapters.BaseSinglePropertyAdapter`2.ResubscribeProperty(TProp newValue)
>    at ReactiveValidation.Adapters.BaseSinglePropertyAdapter`2.RevalidateProperty(String propertyName)
>    at ReactiveValidation.Adapters.BasePropertiesAdapter`2.Revalidate(String propertyName)
>    at ReactiveValidation.ObjectValidator`1.OnObjectPropertyChanged(Object sender, PropertyChangedEventArgs args)
>    at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
>    at ReactiveValidation.ValidatableObject.OnPropertyChanged(String propertyName)
>    at Kontragent.ViewModel.Organization.OrganizationViewModel.set_SelectedSection(SectionViewModel value) in C:\Users\peskov\Desktop\Kontragent 02.09.2020_УТРО\Kontragent 02.09.2020_УТРО\Kontragent.Main\ViewModel\Organization\OrganizationViewModel.cs:line 146
>

**Comment by Karnah** [comment]
Добрый день.
Нашёл ошибку, постараюсь сегодня выпустить исправление

**Comment by PeskovV** [comment]
Не ожидал получить ответ)

**Comment by Karnah** [comment]
@PeskovV, выкатил версию 1.0.6, просьба посмотреть как теперь :)

У меня, к сожалению, не хватает времени, чтобы глобально что-то сделать. Но починить всякую мелочь - не проблема :)

**Comment by PeskovV** [comment]
@Karnah Спасибо больше, скоро посмотрю!
Думаю, что мне стоит и pr присылать, не только issue писать😀

**Comment by Karnah** [comment]
Ну, как говорится, PR всегда приветствуются :)

**Comment by PeskovV** [comment]
@Karnah Спасибо большое, всё работает!

**Comment by Karnah** [comment]
@PeskovV, сейчас выкачу еще версию 1.0.7. К сожалению, я пропустил утечку памяти

**Comment by Karnah** [comment]
@PeskovV, выложил новую версию пакета. Если будет не сложно, то также просьба проверить

**Comment by PeskovV** [comment]
@Karnah Добрый вечер! Вроде бы всё в порядке, проблем не обнаружил. 
Если что-то появится ещё, сообщу.
Спасибо ещё раз!

**Comment by Karnah** [comment]
Отлично, спасибо огромное!
Тогда закрываю эту задачу
