### ISSUE TITLE
Throttle validation

### ISSUE THREAD

**Issue by WizMe-M** [Karnah/ReactiveValidation#28]
Hi, is there some way to throttle validation?
What does I mean. Im searching a method that will work with `.Must()` rule. Guess, it should work similar ReactiveUI:
```
this.WhenAnyValue(model => model.SearchText)
            .Throttle(TimeSpan.FromMilliseconds(400))
            .Subscribe(Find);
```
Explanation: `.Throttle()` will ignore observables while specified `TimeSpan` duration (from last observable property change) won't end. In case above `Find` won't be called if `SearchText` input will be faster than 400ms. If user stops input, then subscribed method starts.

I awaited library contains some rule like this one:
```
builder.RuleFor(model => model.Title)
     .Throttle(new TimeSpan(400))
     .Must(async title => !await ExistsAsync(title));
```
Use case above: observable property `Title` calls `Must`-rule to validate there isn't other model with such `Title`. It will refer to database each time property was changed, so there shouldn't be many queries after new letter inputed.

Maybe it also should be possible to cancel async method with `CancellationToken` from `.Throttle()`.
What do you think?

**Comment by Karnah** [comment]
Hello, @WizMe-M!
This is the nice feature! I'll think about how it's better to implement. Thanks for idea.

**Comment by Karnah** [comment]
Hello, @WizMe-M
I finally did it! I hope it flexible enough to supports most of needs. It allows:
- Set up throttle for each rule individually (`Throttle`) and for all of them (`CommonThrottle`)
- Set up throttle for each property individually with difference `dueTime` (`AddRelatedPropertyThrottle`).

Usages:

```
builder.RuleFor(vm => vm.PhoneNumber)
    .NotEmpty()
    .Matches(@"^\d{11}$")
    .CommonThrottle(2000);

builder.RuleFor(vm => vm.Email)
    .NotEmpty()
    .Must(IsValidEmail)
        .Throttle(1000)
    .AllWhen(vm => vm.IsEmailEnabled)
    .CommonThrottle(throttleBuilder => throttleBuilder
        .AddRelatedPropertyThrottle(vm => vm.IsEmailEnabled, 3000));
```

There are few moments:
- `Throttle` is based on async validation. So if you use it for sync validators, they become async. And you need to wait until async validation ended to check `IsValid`.
BUT `WaitValidatingCompletedAsync` doesn't skip throttle. So if user puts last character and pushes kind of "Continue" button, then he/she will wait `Throttle`+`Async method running` time. It's not so good, but I hope most of the developers will use not so big delay. Nevertheless, I hope I will fix it in the future.
- I used another call order: 'first validator - then setting'.  

I'll publish new nuget-pre package next week. I will be glad for feedback!

**Comment by WizMe-M** [comment]
Hi, @Karnah! It's excellent!
Can't wait to use this feature in my diploma. I will necessary response you, when I'll give it a try

**Comment by Karnah** [comment]
I've release 2.0.3 version (without `pre`). Documentation can be found [here](https://github.com/Karnah/ReactiveValidation/wiki/Delay-before-validation-(property-throttling)).
If you will have some problems or questions, please create new issue or reopen this.
