### ISSUE TITLE
Text represantation for int and double properties

### ISSUE THREAD

**Issue by qrzychu** [Karnah/ReactiveValidation#3]
Hi, 

I've run into a slight issue. When I bind to double or int field, when I change a valid number to a text in textbox, binding engine gets an exception, and new value is not assigned to ValidatableObject, making it still valid.

I know I can set ValidateOnExcpetions in WPF and get a visual error, but that still will not make ValidatableObject invalid.

My solution was to make a text variable that you bind to TextBox and put all validation in a rule for that. Then if it is valid, put the value in proper property. Also, if the double property changes, I have to put new value in text variable. Beware, that in case of double you have to check if the text value change and not modify it if not, or you will not be able to enter a coma (it will immediately be changed back to a value without a coma).

So, could you add a rule for that? In object with one or two int/double properties it's ok, but in objects with 6 it's getting messy. Also, you cannot pass e reference to a property with change notification, so you cannot make a functor. You can reference tha backing filed, but it does not fire OnPropertyChanged.

I was thinking about something along this lines:
` builder.RuleFor(x => x.Int).WithText(x => s.IntText).GreaterThan(0);`

It would sync the two properties and their errors, so that when you bind to text you get also error that says it has to be a number greater than 0.

This would be helpful, since I don't really know Expressions. Below is the logic that I currently use and it works very well:

```
public MyValidation()
        {
            Validator = GetValidator();

            this.WhenAnyValue(x => x.Double).Subscribe(x =>
            {
                double? textValue = DoubleText.ParseDouble();

                if (textValue != null)
                {
                        if (x != textValue)
                            DoubleText= x.ToString(CultureInfo.CurrentUICulture);

                }
                else if(string.IsNullOrEmpty(DoubleText))
                {
                    DoubleText = x.ToString(CultureInfo.CurrentUICulture);
                }
            });

         }

        private IObjectValidator GetValidator()
        {
            var builder = new ValidationBuilder<MyValidation>();

            builder.RuleFor(x => x.Double).GreaterThanOrEqualTo(0);

            builder.RuleFor(x => x.DoubleText).NotEmpty().Must(ValidDouble).WithMessage("Provide number greater or equal to 0");

            return builder.Build(this);
        }

        private bool ValidDouble(string doubleText)
        {
            double? textValue = doubleText.ParseDouble();

            if (textValue != null)
            {
                Double = textValue.Value;
                if (Double < 0)
                    return false;
                return true;
            }

            return false;
        }

// and the parsing extension
public static double? ParseDouble(this string value)
        {
            value = value?.Replace(',', '.');

            if (double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out var textValue))
            {
                return textValue;
            }

            return null;
        }
```
Also, would it be possible that if function in Must throws an exception, it's message is set as error message? It would help in case of more complex rules. I know that alternative is to make more that one rule, but sometimes it requiers doubling too much code. 

This would make this library by far the best on nuget :)

Thanks in advance!

**Comment by Karnah** [comment]
Hello!
Yes, I've thought about this problem. In my applications I always use [Xceed](https://www.nuget.org/packages/Extended.Wpf.Toolkit/) controls like [IntegerUpDown](https://xceed.com/wp-content/documentation/xceed-toolkit-plus-for-wpf/Xceed.Wpf.Toolkit~Xceed.Wpf.Toolkit.IntegerUpDown.html) and [DoubleUpDown](https://xceed.com/wp-content/documentation/xceed-toolkit-plus-for-wpf/Xceed.Wpf.Toolkit~Xceed.Wpf.Toolkit.DoubleUpDown.html). They are allows binding int and double properties and create obvious UI. I'd like recommend you try this controls, may be this are will be helpful.

Nevertheless, I will thought about this case. I already have some idea, may be it will solve the problem.

> Also, would it be possible that if function in Must throws an exception, it's message is set as error message? 

Firstly, I think I have problem with exceptions int the rules. This is in my todo list. 
Secondly, I've thought about method which return ValidationMessage. It will allow return in one method different messages. It seems to me that exceptions a bit complicated method.

**Comment by qrzychu** [comment]
Sure, returning string would be great! null would mean no problems.

Those controls seem like a good idea, but I already done that with a workaround:

```
`
IDisposable BindValues(Expression<Func<CalculationValidation, double>> doubleProperty, Action<string> setText, Func<string> getText)
        {
            return this.WhenAnyValue(doubleProperty).Subscribe(x =>
            {
                double? textValue = getText().ParseDouble();

                if (textValue != null)
                {
                    try
                    {
                        if (x != textValue)
                            setText(x.ToString(CultureInfo.CurrentUICulture));
                    }
                    catch (Exception e)
                    {

                    }
                }
                else if (string.IsNullOrEmpty(getText()))
                {
                    setText(x.ToString(CultureInfo.CurrentUICulture));
                }
            });
        }

    BindValues(x => x.Height, x => HeightText = x, () => HeightText); // usage
`
```

Using expressions you only need expression to the other variable and make the other way binding.

Also, this seems to be not bad idea: [stack](https://stackoverflow.com/questions/1268552/how-do-i-get-a-textbox-to-only-accept-numeric-input-in-wpf)

Maybe after this project I will dive into Expressions and make myself this function. Still, would need shared errors.

**Comment by Karnah** [comment]
This Xceed DoubleUpDown example.
![1](https://user-images.githubusercontent.com/6525732/40266702-82bd659c-5b69-11e8-959e-3d2cf1fc1995.gif)
```
<xctk:DoubleUpDown Value="{Binding Mileage}" />
```
Mileage has double type. When control lost focus reset last success value. It's seems to me that it much simpler.

> Also, this seems to be not bad idea: stack

I've already seen this example but I had some problem with it. May be you can use it.

Now you can create you own validation rule extension. For this create validator:
```
public class CheckValidator<TObject, TProp> : IPropertyValidator<TObject, TProp>
    where TObject : IValidatableObject
{
    private readonly Func<ValidationContext<TObject, TProp>, ValidationMessage> _predicate;

    public CheckValidator(Func<ValidationContext<TObject, TProp>, ValidationMessage> predicate)
    {
        _predicate = predicate;
    }


    public IEnumerable<ValidationMessage> ValidateProperty(ValidationContext<TObject, TProp> context)
    {
        var validationMessage = _predicate.Invoke(context);
        return new[] { validationMessage };
    }

    public IEnumerable<string> RelatedProperties { get; } = new string [0];
}
```
Create extensions:
```
public static class Extensions
{
    public static TNext Check<TNext, TObject, TProp>(
        this IRuleBuilderInitial<TObject, TProp, TNext> ruleBuilder,
        Func<TProp, ValidationMessage> predicate)
            where TNext : IRuleBuilder<TObject, TProp, TNext>
            where TObject : IValidatableObject
    {
        return ruleBuilder.SetValidator(
            new CheckValidator<TObject, TProp>(context => predicate.Invoke(context.PropertyValue)));
    }

    public static TNext Check<TNext, TObject, TProp>(
        this IRuleBuilderInitial<TObject, TProp, TNext> ruleBuilder,
        Func<string, TProp, ValidationMessage> predicate)
            where TNext : IRuleBuilder<TObject, TProp, TNext>
            where TObject : IValidatableObject
    {
        return ruleBuilder.SetValidator(
            new CheckValidator<TObject, TProp>(context => predicate.Invoke(context.PropertyName, context.PropertyValue)));
    }

    public static TNext Check<TNext, TObject, TProp>(
        this IRuleBuilderInitial<TObject, TProp, TNext> ruleBuilder,
        Func<ValidationContext<TObject, TProp>, ValidationMessage> predicate)
            where TNext : IRuleBuilder<TObject, TProp, TNext>
            where TObject : IValidatableObject
    {
        return ruleBuilder.SetValidator(new CheckValidator<TObject, TProp>(predicate));
    }
}
```
And use it!
```
...
    builder.RuleFor(vm => vm.DoubleText).Check(IsValidDouble);
...

private static ValidationMessage IsValidDouble(string doubleText)
{
    if (string.IsNullOrEmpty(doubleText) == true)
        return new ValidationMessage(new StaticStringSource("Text must be not empty"), ValidationMessageType.Error);

    if (double.TryParse(doubleText, out var d) == false)
        return new ValidationMessage(new StaticStringSource("Text is not double"), ValidationMessageType.Error);

    if (d <= 0)
        return new ValidationMessage(new StaticStringSource("Double must be greate than 0"), ValidationMessageType.Error);

    return ValidationMessage.Empty;
}
```

Later I'll create a more convenient constructor for ValidationMessage.
![2](https://user-images.githubusercontent.com/6525732/40266961-4912d764-5b6e-11e8-8720-d7b28b9f18a9.PNG)
![3](https://user-images.githubusercontent.com/6525732/40266962-4932a9cc-5b6e-11e8-966d-eb285ceb88e4.PNG)
![4](https://user-images.githubusercontent.com/6525732/40266963-49513018-5b6e-11e8-9a0a-4904dfc8ac17.PNG)
![5](https://user-images.githubusercontent.com/6525732/40266964-496ffca0-5b6e-11e8-9cac-5bfb946d1d56.PNG)

Issue is still open, I'll try publish update on next week.

**Comment by qrzychu** [comment]
thanks for the response :)

I decided to stick with textbox input filtering, it removes so many problems.

**Comment by Karnah** [comment]
Hi, @qrzychu!
If you are still interested, I've published [2.0.0-pre](https://www.nuget.org/packages/ReactiveValidation.Wpf/2.0.0-pre) where there is more convenient feature:
``` c#
builder
    .TransformToInt(vm => vm.AgeString)
    .NotNull().WithMessage("Age should be valid integer string")
    .Between(18, 35);
```

[Documentation](https://github.com/Karnah/ReactiveValidation/wiki/Property-value-transforming)

**Comment by qrzychu** [comment]
Hi, that's great!

Can I put the transformed value in some int property? The whole issue was that I wanted to do wpf validation and then send valid View model mapped to a model via http.

It would be nice to have that value on hand, so that simple automapper call creates proper model

**Comment by Karnah** [comment]
Sorry, there is no outputting value now. It's needed to create additional property like this:
``` c#
public int Age => int.Parse(AgeString);
public string AgeString { get;set; }
```
or create separate rule for Automapper.

But it doesn't sound like a hard to implement feature. Probably, it can look like this:
``` c#
builder
    .TransformToInt(vm => vm.AgeString, (vm, transformedValue) => vm.Age = transformedValue)
    .NotNull().WithMessage("Age should be valid integer string")
    .Between(18, 35);
```
I'll try some variants and let you know :)
