### ISSUE TITLE
Support Avalonia 11

### ISSUE THREAD

**Issue by blahetal** [Karnah/ReactiveValidation#31]
Hello, would you consider updating the code to support the latest Avalonia 11 which was released last week.

**Comment by Karnah** [comment]
@blahetal. hello!
Sorry, have some trouble with new Avalonia theme system. I hope I will fix it till next Wednesday. Is it OK?

**Comment by blahetal** [comment]
it's fine, no worries

**Comment by blahetal** [comment]
Thanks, if I were you, I would support only Avalonia 11 final release and above (without considering RC's, previews).
I cannot test it right now because in my app I am using some other Avalonia libraries which have not been released for Avalonia 11 yet so release the stable when it suits you :)

**Comment by Karnah** [comment]
Moving from one version of Avalonia to another is a big pain because of breacking changes. I've decided to give opportunity support previous versions a bit more :)

**Comment by Karnah** [comment]
It seems to me that I've waited more than enough :)
I've published release 2.0.4 with support Avalonia 11.0.0 and upper. Please, reopen issue if you will met any problem.
