### ISSUE TITLE
Exception thrown: 'System.ArgumentException' in ReactiveValidation.dll in Output window

### ISSUE THREAD

**Issue by qrzychu** [Karnah/ReactiveValidation#6]
I noticed that I get the following lin ein Output window:

> Exception thrown: 'System.ArgumentException' in ReactiveValidation.dll

The exception itself is:

> Expression '_ => value(ReactiveValidation.Extensions.CommonValidatorsExtensions+<>c__DisplayClass6_0`3[ReactiveValidation.ISinglePropertyRuleBuilder`2[SalesModule.Validation.ItemValidation,System.Double],SalesModule.Validation.ItemValidation,System.Double]).valueToCompare' refers to a field, not a property.

cuased by:

```
var builder = new ValidationBuilder<ItemValidation>();

 builder.RuleFor(x => x.UnitCost).GreaterThanOrEqualTo(0.0);

// UnitCost definition:
 public double UnitCost
        {
            get { return _unitCost; }
            set
            {
                _unitCost = value;
                OnPropertyChanged();

            }
        }
```
https://github.com/qrzychu/ReactiveUserControlBindingSample/tree/validation-sample - reproduction (branch validation-sample)

I'm not sure if this is a problem, because it works in general, but it looks bad when Output window is full of excpetions.

I've found this [post](https://stackoverflow.com/questions/46863529/expression-t-t-someproperty-as-object-refers-to-a-method-not-a-property), maybe it will be helpful

**Comment by Karnah** [comment]
Good day, @qrzychu 
Firstly, I couldn't build your example until update NuGet packages. It's a bit weird.
Secondly, I use VS2017 and I could not reproduce the problem. In my Output window show if exception thrown in code, but not in another dll.

I created PR, which should fix problem. Please try link this code and let me know if it's OK.
Thank you!

**Comment by qrzychu** [comment]
yeah, that helped :)

**Comment by Karnah** [comment]
Closed due to the fact that a lot of time has passed
