### ISSUE TITLE
Nullable properties

### ISSUE THREAD

**Issue by MarkusKgit** [Karnah/ReactiveValidation#9]
Hi,

in my viewmodel I'm binding to nullable types like int? to support initially empty TextBoxes but at the same time getting the benefits of binding to my target type. Now I want to create two rules for my property: the value must not be null and greater than zero.

In FluentValidation I can do it like this:

`RuleFor(x => x.NumberOfCells).NotEmpty().GreaterThan(0);`

With ReactiveValidation the following does not work:

`builder.RuleFor(x => x.NumberOfCells).NotNull().GreaterThan(0);`

That's because the Nullable<> type does not implement IComparable. Is there an easy way around this?

**Comment by Karnah** [comment]
Hello! This is a big flaw! I hope tomorrow I will fix this and update NuGet package.
At this moment the easiest way is using Must(...).

**Comment by MarkusKgit** [comment]
Works like a charm. Thanks for the quick fix and this awesome library :smiley:
